Revise Chapter 6 and 7 to RC02
aas-core-works/aas-core-meta pull request #148
Opened 2022-07-21 10:15 UTC by g1zzm0

Update  Class DataSpecification to RC02
Update  Class DataSpecificationContent to RC02
Update  Class DataTypeIEC61360 to RC02
Update Class DataSpecificationIEC61360 to RC02
Add Class Category_Concept_Description
Update Class DataSpecificationPhysicalUnit  to RC02
Add Chapter Security

2022-07-21 10:36 UTC, g1zzm0 commented
review-requested: @sebbader

2022-07-21 10:38 UTC, g1zzm0 commented
review-requested: @Manu3756

2022-07-21 10:43 UTC, g1zzm0 commented
review-requested: @constantinziesche

2022-07-21 11:53 UTC, mristin commented
@g1zzm0 nitpick: we have to write classes in `Pascal_case` (exception: abbreviations all uppercase except `id`). 

Example: `Data_specification_IEC_631160`

2022-07-21 12:00 UTC, mristin commented
@g1zzm0 the enum `Category_Concept_Description` is indeed redundant. Since `category` is a string attribute, I introduced the constant set `Valid_concept_description_categories`.

2022-07-21 14:44 UTC, sebbader commented
@g1zzm0 honestly, I have a hard time reviewing by the code, is there e.g. a JSON Schema output I can check?

Independently of that, two things from the last working group discussion:
* LangStingSets (https://github.com/aas-core-works/aas-core-meta/blob/4734fff56eef9251e95fc2ca03dbbc23fd0346cc/aas_core_meta/v3rc2.py#L4333) I assume there will be another PR for #128 ?
* HasDataSpecification/embeddedDataSpecification in https://github.com/aas-core-works/aas-core-meta/blob/4734fff56eef9251e95fc2ca03dbbc23fd0346cc/aas_core_meta/v3rc2.py#L1675 will be introduced also in another PR?

2022-07-21 15:01 UTC, g1zzm0 commented
@sebbader As discussed before, the schema generation is done after the validation of the metamodel or now the classes from chapter 6 and 7. The workflow will be Python MM Modeling -> Review MM -> Validation -> Code Generation -> New Schema Generation -> Check MM based on the serialization.  This is necessary to avoid unnecessary correction loops and thus delays.

2022-07-21 16:06 UTC, g1zzm0 commented
@sebbader for the potential change of HasDataSpecification see the branch https://github.com/aas-core-works/aas-core-meta/tree/g1zzm0/EmbeddedDataSpecification

2022-07-22 07:30 UTC, mristin requested changes
Thanks, @g1zzm0!

Most of my suggestions are references and refinement of the comments, so that they are a bit cleaner for the reader (short comments tend to be misread/omitted).

Let's first have others review this code and we merge in this pull request.

Afterwards, I'll write the invariants and double-check the code against the book once more.

2022-07-22 07:30 UTC, mristin commented on aas_core_meta/v3rc2.py
> +        DataSpecificationIEC61360/valueList shall be empty and vice versa.
@g1zzm0 I'll add the invariants in the next step once we merge this PR.

2022-07-22 07:30 UTC, mristin commented on aas_core_meta/v3rc2.py
> +        DataSpecification-IEC61360/preferredName shall be provided at least in English.
```suggestion
        :attr:`~preferred_name` shall be provided at least in English.
```

2022-07-22 07:30 UTC, mristin commented on aas_core_meta/v3rc2.py
> +        with data specification DataSpecificationPhysicalUnit with the same ID.
```suggestion
        Although the :attr:`~unit_id` is a global reference there might exist a 
        :class:`.Concept_description`
        with data specification :class:`.Data_specification_physical_unit` with
        the same ID.
```

2022-07-22 10:20 UTC, sebbader commented
> @sebbader for the potential change of HasDataSpecification see the branch https://github.com/aas-core-works/aas-core-meta/tree/g1zzm0/EmbeddedDataSpecification

As written, fine with me to have it in another step 👍

2022-07-22 10:23 UTC, sebbader commented
> @sebbader As discussed before, the schema generation is done after the validation of the metamodel or now the classes from chapter 6 and 7. The workflow will be Python MM Modeling -> Review MM -> Validation -> Code Generation -> New Schema Generation -> Check MM based on the serialization. This is necessary to avoid unnecessary correction loops and thus delays.

Then I regard my review as finished for now 👍 . Looks good to me but I am far away of being able to detect issues based on the python file 😄

2022-07-22 18:25 UTC, mristin commented
@all please send your reviews till Tuesday 17h CET, so that we can continue with the changes and avoid conflicts. If there are more points, please open an issue.

2022-07-28 09:45 UTC, g1zzm0 commented on aas_core_meta/v3rc2.py
> +    Relationship = "RELATIONSHIP"
For the sake of completeness, we will keep this in the initial 1:1 commit for now.

2022-07-29 09:10 UTC, mristin approved these changes

2022-07-29 09:11 UTC, mristin commented
@g1zzm0 I reviewed your latest commits -- thanks, all LGTM!

2022-08-01 08:20 UTC, merged