V3 bugfixes
aas-core-works/aas-core-meta pull request #189
Opened 2023-02-07 08:58 UTC by s-heppner

This fixes bugs and findings after a preliminary review of the v3.0 implementations. 

Note, that before v3.0 can be considered done, the following issues remain:

- The AAS/Aas, XSD/Xsd abbreviation mess (#177)
- Data_specification_physical_unit changes, that are still yet being specified at this moment (#188)

2023-02-08 13:48 UTC, BirgitBoss requested changes
see questions

2023-02-08 13:48 UTC, BirgitBoss commented on aas_core_meta/v3.py
> +    value: Optional["Lang_string_short_name_type_iec_61360"]
Why is the name of the type "Lang_string_short_name_type_iec_61360" and not just "Short_name_type_iec_61360" as specified? Similar for other types starting with Lang_string

2023-02-08 13:48 UTC, BirgitBoss commented on aas_core_meta/v3.py
> +        max: "bool",
why did you change the order? the order is min, max, nom, typ

2023-02-10 08:54 UTC, mristin commented
Closing since it will be fixed/merged in a series of separate pull requests.

2023-02-10 08:54 UTC, closed without merging